name: Link Checker

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC

jobs:
  link-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check Links
        uses: lycheeverse/lychee-action@v1.9.0
        with:
          args: 'directory.md'
          fail: true
